### PR TITLE
(Incomplete) Add mobile styles

### PR DESCRIPTION
**Pull request by hawkins**
Hey again,

So this PR is marked incomplete because it's not completely finished yet imo. The groundwork has been laid though, and I already enjoy using it significantly more on mobile now, so I thought I'd open this PR in order to let you take a look and provide feedback before too much time has passed if you so desired.

In a nutshell, here's the status of the PR as of opening this:

### TODO: 

- [x] Change viewport to support mobile 
- [ ] Adjust media items for smaller screens
  - [x] Resize to fill width
  - [ ] Retain original margins / spacing
  - [ ] Resize play button shadow to match
- [x] Adjust navigation bar for smaller screens
  - [x] Implement a new layout for smaller screens
- [ ] Adjust video player for smaller screens
  - [ ] Resize player component
    - Only so necessary, since mobile phones will use the native video players anyways (iOS curently does this)
  - [ ] Determine a solution for including emoji reactions, or exclude from mobile
- [ ] Undo prettier's formatting (new editor, oops!)
- [ ] Remove shrinkwraps

For convenience sake, I'll target PWA in a separate PR later, once the dust has settled on this one.

---

At this point, I'm not sure how best to deal with retaining original margin between elements now that they're resized using tachyons. I suppose we could create new `w-100-p` or similar class to that would have a width of near 100% but leave room for some small margins on the side, but I was hoping to stay true to tachyon's provided styles. Any advice on how you would approach this?

The rest should be fairly trivial, excluding player emojis, but with the holiday season and my moving, it may take me some time to get around to it.

### CODE REVIEW

**Comment by hawkins** [comment]
Heads up for anyone curious, I'm nearing the end of my hiatus and hope to resume this in a week or two. 😄

**Comment by remixz** [comment]
👍 Excited to see what's in store! I'm in the middle of starting a new job *and* moving so I don't have a ton of free time, but I'll hopefully be able to review it soon after you continue on it. 😄

**Comment by hawkins** [comment]
Very cool, I just did the same! I'll tinker with this some tonight and see if I can't make any progress on it.

**Comment by remixz** [comment]
@hawkins Just so you know, I made an update to Umi for a "host-only mode" for rooms, where a creator of a room can toggle it on, and then they're the only ones who can control the player. (Commit: https://github.com/remixz/umi/commit/37f36b11fcbb0f472002043b1d1d66d10e554f18) Once you start work on this, you'll have to rebase your PR. Sorry for the hassle 😂

**Comment by hawkins** [comment]
Not a problem, I’m not actually very familiar with rebasing, so this’ll be a fine opportunity to get acquainted!

**Comment by remixz** [comment]
Just looking at this PR a bit; if you'd like you can actually keep the `prettier` formatting, as I've been meaning to add that anyway! 😄 Here are the options I'd like to use (you can add this in `package.json`):


```json
"prettier": {
  "semi": false,
  "singleQuote": true,
  "arrowParens": "always"
}
```

**Comment by hawkins** [comment]
Hey @remixz, I’m sad to say I think I’m going to have to call this PR dead and close it :( I’ve not adjusted well to moving and haven’t been able to find motivation to code after my new job, so my time spent on open source has slowed to a halt. Sorry about that. I wouldn’t mind at all if someone picked up the effort or started over from scratch, but I just don’t think I have the time needed to finish this from here. Sorry about that!

Still love Umi though, and I’ll be sure to come back and properly contribute once my motivation for hobbies is back in order. Keep up the great work in the mean time!!

**Comment by remixz** [comment]
@hawkins Absolutely no worries at all!! Moving is intense 😅 I have no idea how far you moved, but even if it was close, any move is a big adjustment! Plus combined with a new job... yup, totally understand. 

I hope you get on your feet soon (I think you will!), and hopefully in the meantime you can use Umi to watch some anime and destress a little. 😄 Thanks for starting this, I might play with it a bit more and see what I can do. If not, well... there'll be something to do if you decide to contribute again! 😂 Best wishes man, good luck with the new job!

**Pull request closed without merging**
